/*
 * Data Service API
 * Внутренний API для управления студентами. Этот сервис отвечает за чтение и запись данных в базу данных. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.khrisanfova.gate.client.api;

import org.junit.jupiter.api.Test;
import ru.khrisanfova.gate.client.model.StudentDataCreateRequest;

/**
 * Model tests for StudentDataCreateRequest
 */
class StudentDataCreateRequestTest {
    private final StudentDataCreateRequest model = new StudentDataCreateRequest();

    /**
     * Model tests for StudentDataCreateRequest
     */
    @Test
    void testStudentDataCreateRequest() {
        // TODO: test StudentDataCreateRequest
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'passport'
     */
    @Test
    void passportTest() {
        // TODO: test passport
    }

}
